name: flutter_library
description: A Flutter library
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  matrix_gesture_detector: ^0.1.0
  scoped_model: ^1.0.1

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/dog.jpg
    - assets/images/background.jpg

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf