name: flutter_library
description: A Flutter library
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  matrix_gesture_detector: ^0.1.0
  provider: ^3.0.0+1
  scoped_model: ^1.0.1
  flutter_svg: ^0.12.4+2
  flutter_launcher_icons: ^0.7.2
  shared_preferences: ^0.5.3+1
  flutter_secure_storage: ^3.2.1+1
  json_annotation: ^2.0.0
  event_taxi: ^0.1.5
  http: ^0.12.0+2
  dafluta: ^1.4.0
  dahttp: ^1.2.0
  dalocale: ^1.2.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  build_runner: ^1.6.0
  json_serializable: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon.png"
  # flutter pub run flutter_launcher_icons:main

flutter:

  uses-material-design: true

  assets:
    # icons
    - assets/icons/smile.svg
    - assets/icons/smile.png

    # images
    - assets/images/dog.jpg
    - assets/images/background.jpg

    # gifs
    - assets/gifs/loading.gif

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf